### ISSUE TITLE
Getting this error when notification is received,findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by saudkhan1391** [tjrexer/react-notifications#21]
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of CSSTransitionGroupChild which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

**Comment by saudkhan1391** [comment]
Any solutions ?

**Comment by tjrexer** [comment]
It might be fixed by PR #20 since it changes how the CSS Transition Group is used.  I'll let you know when that is merged, and you can see if that fixes your issue.

**Comment by saudkhan1391** [comment]
Thanks. I'ill be waiting for the merge.

**Comment by tjrexer** [comment]
Just published 1.7.0 which includes updates to `react-transition-group`.  Check to see if that resolves your issue.

**Comment by ogzhnozlci** [comment]
**1.7.2** version, this warning is still logging while notification is appearing

**Comment by brenobaptista** [comment]
@tjrexer https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md#features
I don't see `nodeRef` prop being created and passed through `CSSTransition` and `Notification`, maybe that's why we are still getting this warning?

**Comment by karelkryda** [comment]
same. No solution?

**Comment by saudkhan1391** [comment]
This was fixed I think.

**Comment by karelkryda** [comment]
@saudkhan1391 I'm still getting this error in console
![image](https://user-images.githubusercontent.com/59953812/112645346-ac081d80-8e46-11eb-84f4-c0fd102973d0.png)

**Comment by karelkryda** [comment]
![image](https://user-images.githubusercontent.com/59953812/112646406-b8d94100-8e47-11eb-9925-e53f2849f0e7.png)

**Comment by saudkhan1391** [comment]
Don't use in strictMode. Try using it inside <Router or <appoloProvide .

**Comment by karelkryda** [comment]
@saudkhan1391 still same, I triend inside Apollo and also inside Router
![image](https://user-images.githubusercontent.com/59953812/112678616-6c076180-8e6b-11eb-92f9-b856a76e5cc1.png)

**Comment by marcosdipaolo** [comment]
no answer to this?

Also tried inside `Router` and i still get the warning

**Comment by alexshmyrkov** [comment]
The issue still persists in the latest build.

**Comment by tjrexer** [comment]
I have not been able to find anything causing the warning. Only warnings I'm seeing is regarding componentWillX & am working on that fix.

**Comment by evpozdniakov** [comment]
It can be fixed like this: https://github.com/reactjs/react-transition-group/issues/904#issuecomment-2564990394
